from .tools import (
    get_defect_summary,
    get_defect_map,
    get_defects,
    get_fdc_traceback,
    get_equipment_health,
    get_trace_summary,
    get_param_drift,
    get_trace_compare,
    get_equipment_list,
    get_equipment_detail,
    get_trace_latest,
    get_trace_oos,
    get_trace_data,
    get_alarms,
    get_alarm_summary,
    get_alarm_trend,
    get_events,
    get_event_timeline,
    get_param_correlation,
)


def get_fab_trace_tools() -> list:
    """Fab Trace 시나리오 1 (불량률 상승 원인 추적) 도구 목록 반환"""
    return [
        get_defect_summary,
        get_defect_map,
        get_defects,
        get_fdc_traceback,
        get_equipment_health,
        get_trace_summary,
        get_param_drift,
        get_trace_compare,
        get_equipment_list,
        get_equipment_detail,
        get_trace_latest,
        get_trace_oos,
        get_trace_data,
        get_alarms,
        get_alarm_summary,
        get_alarm_trend,
        get_events,
        get_event_timeline,
        get_param_correlation,
    ]
